#2022년 1월의 도서 판매 데이터를 기준으로 
#저자 별, 카테고리 별 매출액(TOTAL_SALES = 판매량 * 판매가) 을 구하여, 
#저자 ID(AUTHOR_ID), 저자명(AUTHOR_NAME), 카테고리(CATEGORY), 매출액(SALES) 출력
#저자 ID를 오름차순으로, 카테고리를 내림차순

# WITH AUTHOR_BOOK AS(
#     SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, B.PRICE, B.BOOK_ID
#     FROM AUTHOR A INNER JOIN BOOK B ON A.AUTHOR_ID=B.AUTHOR_ID)

SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(S.SALES*B.PRICE) AS TOTAL_SALES
FROM AUTHOR A 
        INNER JOIN BOOK B ON A.AUTHOR_ID=B.AUTHOR_ID
        INNER JOIN BOOK_SALES S ON B.BOOK_ID=S.BOOK_ID
WHERE MONTH(S.SALES_DATE)=01
GROUP BY B.AUTHOR_ID, B.CATEGORY
ORDER BY B.AUTHOR_ID, B.CATEGORY DESC