SELECT SEC_C.ID
FROM 
    ECOLI_DATA SEC_C INNER JOIN (
    SELECT FIRST_C.ID
    FROM ECOLI_DATA FIRST_C INNER JOIN ECOLI_DATA PAR
    ON FIRST_C.PARENT_ID=PAR.ID
    WHERE PAR.PARENT_ID IS NULL) FIRST_CC
WHERE SEC_C.PARENT_ID = FIRST_CC.ID
ORDER BY SEC_C.ID
