SELECT E.ID, COALESCE(EP.CHILD_COUNT,0) AS CHILD_COUNT
FROM
    ECOLI_DATA E LEFT JOIN 
        (SELECT PARENT_ID, COUNT(PARENT_ID) AS CHILD_COUNT
        FROM ECOLI_DATA
        GROUP BY PARENT_ID
        ORDER BY PARENT_ID) EP ON E.ID=EP.PARENT_ID
ORDER BY E.ID