#자동차 종류가 '세단' 또는 'SUV' 인 자동차 중 
#2022년 11월 1일부터 2022년 11월 30일까지 대여 가능하고 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차에 대해서 
#자동차 ID, 자동차 종류, 대여 금액(컬럼명: FEE) 리스트를 출력
#대여 금액을 기준으로 내림차순, 자동차 종류를 기준으로 오름차순, 자동차 ID를 기준으로 내림차순 정렬

WITH CAR_TYPE_TABLE AS (
        SELECT CAR_ID, CAR_TYPE, DAILY_FEE
        FROM CAR_RENTAL_COMPANY_CAR
        WHERE CAR_TYPE='SUV' OR CAR_TYPE='세단'),
    
    CAR_DATE_TABLE AS (
        SELECT CAR_ID 
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE CAR_ID NOT IN (
            # 11월달에 빌린경우
            SELECT CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
            WHERE MONTH(START_DATE)<=11 AND (MONTH(END_DATE)>=11 OR YEAR(END_DATE)>2022)
            )
        GROUP BY CAR_ID
        ORDER BY CAR_ID
        ),
        
    CAR_DISCOUNT_TABLE AS(
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE LIKE "30%")
    
SELECT 
    T.CAR_ID,
    T.CAR_TYPE,
    ROUND(30*(T.DAILY_FEE - ((REGEXP_REPLACE(P.DISCOUNT_RATE,'%[^0-9]%',' ')/100) * T.DAILY_FEE)), 0) AS FEE
FROM 
    CAR_TYPE_TABLE T 
    INNER JOIN CAR_DATE_TABLE D ON T.CAR_ID=D.CAR_ID
    INNER JOIN CAR_DISCOUNT_TABLE P ON T.CAR_TYPE=P.CAR_TYPE
# GROUP BY T.CAR_ID
WHERE  ROUND(30*(T.DAILY_FEE - ((REGEXP_REPLACE(P.DISCOUNT_RATE,'%[^0-9]%',' ')/100) * T.DAILY_FEE)), 0) BETWEEN 500000 AND 2000000
ORDER BY
    FEE DESC, T.CAR_TYPE, T.CAR_ID DESC