SELECT O.YEAR, O.MONTH, U.GENDER, COUNT(DISTINCT O.USER_ID) AS USERS
FROM 
    (SELECT USER_ID, GENDER
    FROM
        USER_INFO 
    WHERE GENDER IS NOT NULL) U
    INNER JOIN 
    (SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, USER_ID
    FROM 
        ONLINE_SALE)O 
    ON U.USER_ID=O.USER_ID
GROUP BY YEAR,MONTH,GENDER
ORDER BY YEAR,MONTH,GENDER

# SELECT * FROM USER_INFO