#2021년에 가입한 전체 회원들 중 상품을 구매한 회원수,
#(2021년에 가입한 회원 중 상품을 구매한 회원수 / 2021년에 가입한 전체 회원 수)을 년, 월 별로 출력
# 회원의 비율은 소수점 두번째자리에서 반올림
#년,월 오름차순

WITH JOIN_IN_2021 AS (
    SELECT USER_ID
    FROM USER_INFO 
    WHERE YEAR(JOINED)=2021
)

SELECT 
    YEAR(SALES_DATE) AS YEAR, 
    MONTH(SALES_DATE) AS MONTH,
    COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS,
    ROUND((COUNT(DISTINCT O.USER_ID)/(SELECT COUNT(*) FROM JOIN_IN_2021)),1) AS PUCHASED_RATIO
FROM 
    ONLINE_SALE O 
    INNER JOIN JOIN_IN_2021 J ON O.USER_ID=J.USER_ID
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE)
    
    
