WITH RECURSIVE GENTABLE AS(
    SELECT ID, PARENT_ID, 1 AS GENERATE
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION
    SELECT E.ID, E.PARENT_ID, (G.GENERATE+1) AS GENERATE
    FROM ECOLI_DATA E INNER JOIN GENTABLE G ON E.PARENT_ID=G.ID
    WHERE E.PARENT_ID=G.ID
)

SELECT COUNT(*) AS COUNT, GENERATE AS GENERATION
FROM GENTABLE
WHERE ID NOT IN (SELECT PARENT_ID FROM GENTABLE WHERE PARENT_ID IS NOT NULL)
GROUP BY 2
ORDER BY 2