#아직 입양을 못 간 동물 중, 가장 오래 보호소에 있었던 동물 3마리의 이름과 보호 시작일을 조회
#보호 시작일 순으로 조회

WITH NOT_OUT AS (
    SELECT I.ANIMAL_ID
    FROM ANIMAL_INS I 
    LEFT JOIN ANIMAL_OUTS O ON I.ANIMAL_ID=O.ANIMAL_ID
    WHERE O.ANIMAL_ID IS NULL
)

SELECT NAME, DATETIME
FROM ANIMAL_INS
WHERE 
    ANIMAL_ID IN (SELECT ANIMAL_ID FROM NOT_OUT)
ORDER BY DATETIME
LIMIT 3