# 생산일자(PRODUCE_DATE)가 2022년 5월인 식품들의 식품 ID, 식품 이름, 총매출(PRICE*AMOUNT)을 조회
# 총매출을 기준으로 내림차순, 식품 ID를 기준으로 오름차순

SELECT F.PRODUCT_ID, P.PRODUCT_NAME, SUM(P.PRICE*F.AMOUNT) AS TOTAL_SALES
FROM FOOD_ORDER F 
    INNER JOIN FOOD_PRODUCT P ON F.PRODUCT_ID=P.PRODUCT_ID
WHERE 
    YEAR(F.PRODUCE_DATE)=2022 AND MONTH(F.PRODUCE_DATE)=5
GROUP BY 1
ORDER BY 
    3 DESC, 1


