# 7월 아이스크림 총 주문량과 상반기의 아이스크림 총 주문량을 더한 값이 큰 순서대로 
# 상위 3개의 맛을 조회

WITH F_TABLE AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS SUMT
    FROM FIRST_HALF
    GROUP BY FLAVOR
),
J_TABLE AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS SUMT
    FROM JULY
    GROUP BY FLAVOR)

SELECT F.FLAVOR
FROM F_TABLE F INNER JOIN J_TABLE J ON F.FLAVOR=J.FLAVOR
GROUP BY F.FLAVOR
ORDER BY F.SUMT+J.SUMT DESC
LIMIT 3