WITH RECURSIVE HOUR_CTE (HOUR) AS(
    SELECT 0
    
    UNION ALL
    
    SELECT HOUR+1
    FROM HOUR_CTE
    WHERE HOUR<23)
    
SELECT H.HOUR, 
    CASE 
    WHEN A.COUNT IS NULL THEN 0
    ELSE A.COUNT END AS COUNT
FROM (SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
      FROM
      ANIMAL_OUTS 
      GROUP BY 1
      ORDER BY 1)A RIGHT JOIN HOUR_CTE H ON A.HOUR=H.HOUR