# DEVELOPERS 테이블에서 Front End 스킬을 가진 개발자의 정보
# 개발자의 ID, 이메일, 이름, 성을 조회
# ID를 기준으로 오름차순

WITH FRONTEND AS(
    SELECT BIT_OR(CODE)
    FROM SKILLCODES
    GROUP BY CATEGORY
    HAVING CATEGORY="Front End"
)

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM 
    DEVELOPERS 
WHERE (SELECT * FROM FRONTEND)&SKILL_CODE>0
ORDER BY 1
