# 리뷰를 가장 많이 작성한 회원의 리뷰들을 조회
# 회원 이름, 리뷰 텍스트, 리뷰 작성일
# 리뷰 작성일, 리뷰 텍스트를 기준으로 오름차순

WITH WHO_TABLE AS (
SELECT MEMBER_ID
     FROM REST_REVIEW 
     GROUP BY MEMBER_ID 
     ORDER BY COUNT(REVIEW_ID) DESC 
     LIMIT 1)

SELECT 
    M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE,"%Y-%m-%d") as REVIEW_DATE
FROM 
    MEMBER_PROFILE M 
    INNER JOIN REST_REVIEW R ON M.MEMBER_ID=R.MEMBER_ID
WHERE R.MEMBER_ID IN
    (SELECT MEMBER_ID FROM WHO_TABLE)
ORDER BY 3, 2
