# 부모의 형질을 모두 보유한 대장균의 ID(ID), 대장균의 형질(GENOTYPE), 부모 대장균의 형질(PARENT_GENOTYPE)을 출력
# ID 오름차순

SELECT C.ID,C.GENOTYPE,P.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA P INNER JOIN ECOLI_DATA C ON P.ID=C.PARENT_ID
WHERE (P.GENOTYPE&C.GENOTYPE)=P.GENOTYPE
ORDER BY 1