#보호 시작일(I.DATETIME)보다 입양일(O.DATETIME)이 더 빠른 동물의 아이디와 이름을 조회
#보호 시작일이 빠른 순

SELECT I.ANIMAL_ID, I.NAME
FROM 
    ANIMAL_INS I 
    INNER JOIN ANIMAL_OUTS O ON I.ANIMAL_ID=O.ANIMAL_ID
WHERE
    I.DATETIME>O.DATETIME
# GROUP BY I.ANIMAL_ID
ORDER BY I.DATETIME