WITH DATE_TABLE AS(
    SELECT
        MONTH(START_DATE) AS MONTH,
        CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE YEAR(START_DATE)=2022 AND MONTH(START_DATE) BETWEEN 8 AND 10),
    
    ID_RENT_FIVE AS(
        SELECT CAR_ID
        FROM DATE_TABLE
        GROUP BY CAR_ID
        HAVING COUNT(*)>=5
    )
    
SELECT
    MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM
    DATE_TABLE
WHERE CAR_ID IN (SELECT CAR_ID FROM ID_RENT_FIVE)
GROUP BY MONTH, CAR_ID
ORDER BY MONTH, CAR_ID DESC