SELECT 
    E.YEAR, C.MAX_SIZE-E.SIZE_OF_COLONY AS YEAR_DEV, E.ID
FROM 
    (SELECT 
        YEAR(DIFFERENTIATION_DATE) AS YEAR, 
        SIZE_OF_COLONY, 
        ID
      FROM 
        ECOLI_DATA) E 
        INNER JOIN 
    (SELECT 
        YEAR(DIFFERENTIATION_DATE) AS YEAR, 
        MAX(SIZE_OF_COLONY) AS MAX_SIZE 
     FROM 
        ECOLI_DATA
     GROUP BY 
        YEAR(DIFFERENTIATION_DATE)) C ON E.YEAR=C.YEAR
ORDER BY YEAR, YEAR_DEV