# 조회수가 가장 높은 중고거래 게시물에 대한 첨부파일 경로를 조회

WITH VIEW_TOP AS (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD 
    ORDER BY VIEWS DESC
    LIMIT 1
)

SELECT 
    CONCAT("/home/grep/src/",U.BOARD_ID,"/",U.FILE_ID,U.FILE_NAME,U.FILE_EXT) 
    AS FILE_PATH
FROM VIEW_TOP T INNER JOIN USED_GOODS_FILE U ON T.BOARD_ID=U.BOARD_ID
ORDER BY U.FILE_ID DESC