WITH SALES_TABLE AS 
    (SELECT BOOK_ID, SUM(SALES) AS SALES
    FROM BOOK_SALES
     WHERE SALES_DATE BETWEEN "2022-01-01" AND "2022-01-31"
    GROUP BY BOOK_ID)

SELECT B.CATEGORY, SUM(S.SALES) AS SALES
FROM SALES_TABLE AS S INNER JOIN BOOK B ON S.BOOK_ID=B.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY